# Generated by Django 5.0.1 on 2024-02-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_table_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.IntegerField()),
            ],
        ),
    ]
