# Generated by Django 5.0.1 on 2024-02-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_tablebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='image',
            field=models.ImageField(default='', upload_to='portal/images'),
        ),
    ]
