# Generated by Django 5.0.1 on 2024-02-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_tablebooking_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='image',
        ),
    ]
