# Generated by Django 5.0.1 on 2024-02-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_party_size_tablebooking_partysize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='partysize',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='time',
        ),
    ]
