# Generated by Django 5.0.1 on 2024-02-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_tablebooking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='image',
            field=models.ImageField(default='', upload_to='portal/images'),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='partysize',
            field=models.IntegerField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
