# Generated by Django 5.0.1 on 2024-02-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_tablebooking_image_tablebooking_partysize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='partysize',
        ),
    ]
